Repository yash19sinha/coffee-bean, pull requests merged in 2023-10, with the labels that each got.

#24 Fix an issue in Features in small screens
  css/styles.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#23 Center testimonial section
  css/styles.css
Labels: enhancement, good first issue, hacktoberfest

#28 Sweet alert added
  cart.js
  index.html
  payment.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#43 Fix UI error
  css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#41 improved navbar and scrollbar
  cart.js
  css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#38 Feature/random quote
  cart.js
  index.html
  netbank.js
  payment.html
Labels: hacktoberfest, hacktoberfest-accepted

#48 Fixes#46 The bug of White Line.
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#53 update photos of starbucks and costa coffee logos
  img/press/costa-coffee.jpg
  img/press/costa.png
  img/press/starbucks.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#76 Update: color combination in navbar
  css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#86 Fixed the overflow of heading in the price section.
  css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#87 Enhance the styling
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#93 fix: improper transition effect applied for buttons during hover ⚒️✨
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#96 Dynamic changing caraousel and heading of Our Testimonials Added
  css/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#103 made navbar design responsive to other devices resolutions
  css/styles.css
Labels: hacktoberfest, hacktoberfest-accepted
